backend:
  name: github
  repo: VojtechPetr/MeBS-Hodonin
  branch: main

media_folder: 'public/assets/images'
public_folder: 'src/assets/images'

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/content/post'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - { label: 'Image', name: 'image', widget: 'string' }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }

  - label: 'Rozdělení SVJ'
    name: 'rozdeleni_svj'
    files:
      - label: 'Rozdělení SVJ'
        name: 'rozdeleni_svj'
        file: 'src/content/editable/rozdeleni-svj.yml'
        fields:
          - label: 'Kanceláře'
            name: 'kancelare'
            widget: 'list'
            fields:
              - { label: 'Číslo', name: 'cislo', widget: 'string' }
              - { label: 'Barva', name: 'barva', widget: 'string' }
              - { label: 'Správce', name: 'spravce', widget: 'string' }
              - label: 'Nemovitosti'
                name: 'nemovitosti'
                widget: 'list'
                fields:
                  - { label: 'Adresa', name: 'adresa', widget: 'string' }
          - label: 'Bytová Družstva'
            name: 'bytova_druzstva'
            widget: 'list'
            fields:
              - { label: 'Název', name: 'nazev', widget: 'string' }

  - label: 'Dokumenty BD Kaštany'
    name: 'bd_kastany'
    folder: 'public/assets/files/bd-kastany'
    create: true
    media_folder: ''
    public_folder: ''
    fields:
      - label: 'Soubory'
        name: 'soubory'
        widget: 'list'
        fields:
          - { label: 'Název souboru', name: 'title', widget: 'string' }
          - { label: 'Soubor', name: 'file', widget: 'file' }

  - label: 'Dokumenty BD Pastelky'
    name: 'bd_pastelky'
    media_folder: 'public/assets/files/bd-pastelky'
    public_folder: '/assets/files/bd-pastelky'
    files:
      - label: 'Soubory'
        name: 'soubory'
        file: ''
        fields:
          - { label: 'Název', name: 'name', widget: 'string' }
          - { label: 'Soubor', name: 'file', widget: 'file' }
