backend:
  name: github
  repo: VojtechPetr/MeBS-Hodonin
  branch: main
  client_id: 'Ov23li4P1rJmx2UWaWmP'
  scope: 'repo'
  base_url: 'https://mebs-hodonin-oauth.vercel.app'
  auth_endpoint: 'auth'

media_folder: 'public/assets/images'
public_folder: 'src/assets/images'

collections:
  #rozdeleni SVJ
  - label: 'SVJ/Rozdělení SVJ'
    name: 'rozdeleni_svj'
    files:
      - label: 'Rozdělení SVJ'
        name: 'rozdeleni_svj'
        file: 'src/content/editable/rozdeleni-svj.yml'
        fields:
          - label: 'Kanceláře'
            name: 'kancelare'
            widget: 'list'
            fields:
              - { label: 'Číslo', name: 'cislo', widget: 'string' }
              - { label: 'Barva', name: 'barva', widget: 'string' }
              - { label: 'Správce', name: 'spravce', widget: 'string' }
              - label: 'Nemovitosti'
                name: 'nemovitosti'
                widget: 'list'
                fields:
                  - { label: 'Adresa', name: 'adresa', widget: 'string' }
          - label: 'Bytová Družstva'
            name: 'bytova_druzstva'
            widget: 'list'
            fields:
              - { label: 'Název', name: 'nazev', widget: 'string' }

  #cenik
  - name: 'cenik'
    label: 'SVJ/Ceník'
    files:
      - label: 'Ceník 2024'
        name: 'SVJ/Ceník_2024'
        file: 'src/content/editable/cenik.yml'
        format: 'yml'
        fields:
          - label: 'Položky ceníku'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Název služby', name: 'service', widget: 'string' }
              - { label: 'MěBS (částka)', name: 'price', widget: 'string' }
              - { label: 'Cena s DPH', name: 'price_with_tax', widget: 'string' }
          - label: 'Titulek (Hero)'
            name: 'hero_title'
            widget: 'string'
          - label: 'Podtitulek (Hero)'
            name: 'hero_subtitle'
            widget: 'text'
          - label: 'Zápatí text 1'
            name: 'footer_text_1'
            widget: 'string'
          - label: 'Zápatí text 2'
            name: 'footer_text_2'
            widget: 'string'
          - label: 'Zápatí text 3'
            name: 'footer_text_3'
            widget: 'string'

    # Kontakty SVJ
  - name: 'svj-kontakty'
    label: 'SVJ/Kontakty'
    files:
      - label: 'Kontakty SVJ'
        name: 'svj-kontakty'
        file: 'src/content/editable/svj-kontakty.yml'
        format: 'yml'
        fields:
          - label: 'Kontakty'
            name: 'contacts'
            widget: 'list'
            fields:
              - { label: 'Jméno', name: 'name', widget: 'string' }
              - { label: 'Pozice', name: 'title', widget: 'string' }
              - { label: 'Ikona', name: 'icon', widget: 'string' }
              - label: 'Kontaktní informace'
                name: 'contactInfo'
                widget: 'list'
                fields:
                  - { label: 'Typ', name: 'type', widget: 'select', options: ['phone', 'email'] }
                  - { label: 'Hodnota', name: 'value', widget: 'string' }

    #údržba
  - label: 'Udržba'
    name: 'realizovane_akce'
    files:
      - label: 'Realizované akce 20XX'
        name: 'realizovane_akce_2024'
        file: 'src/content/editable/udrzba.yml'
        fields:
          - label: 'Titul'
            name: 'title'
            widget: 'string'
          - label: 'Položky'
            name: 'items'
            widget: 'list'
            fields:
              - label: 'Titul položky'
                name: 'title'
                widget: 'string'

  #kontakty údržba
  - name: 'udrzba-kontakty'
    label: 'Údržba/Kontakty'
    files:
      - label: 'Kontakty údržby'
        name: 'udrzba-kontakty'
        file: 'src/content/editable/udrzba-kontakty.yml'
        format: 'yml'
        fields:
          - label: 'Kontakty'
            name: 'contacts'
            widget: 'list'
            fields:
              - { label: 'Jméno', name: 'name', widget: 'string' }
              - { label: 'Pozice', name: 'title', widget: 'string' }
              - { label: 'Ikona', name: 'icon', widget: 'string' }
              - label: 'Kontaktní informace'
                name: 'contactInfo'
                widget: 'list'
                fields:
                  - { label: 'Typ', name: 'type', widget: 'select', options: ['phone', 'email'] }
                  - { label: 'Hodnota', name: 'value', widget: 'string' }

  #teplo
  - name: 'teplo'
    label: 'Teplo'
    files:
      - label: 'Tepelné hospodářství'
        name: 'teplo'
        file: 'src/content/editable/teplo.yml'
        fields:
          - label: 'Plánované opravy'
            name: 'planned_repairs'
            widget: 'object'
            fields:
              - { label: 'Titul', name: 'title', widget: 'string' }
              - { label: 'Podtitul', name: 'subtitle', widget: 'string' }
              - label: 'Položky'
                name: 'items'
                widget: 'list'
                fields:
                  - { label: 'Titul', name: 'title', widget: 'string' }
                  - { label: 'Ikona', name: 'icon', widget: 'string' }

          - label: 'Průběh topné sezóny'
            name: 'heating_season'
            widget: 'object'
            fields:
              - { label: 'Titul', name: 'title', widget: 'string' }
              - label: 'Položky'
                name: 'items'
                widget: 'list'
                fields:
                  - { label: 'Popis', name: 'description', widget: 'markdown' }
                  - { label: 'Ikona', name: 'icon', widget: 'string' }

          - label: 'Tvorba cen tepla'
            name: 'pricing'
            widget: 'object'
            fields:
              - { label: 'Titul', name: 'title', widget: 'string' }
              - label: 'Položky'
                name: 'items'
                widget: 'list'
                fields:
                  - { label: 'Titul', name: 'title', widget: 'string', required: false }
                  - { label: 'Popis', name: 'description', widget: 'markdown' }
                  - { label: 'Ikona', name: 'icon', widget: 'string' }

  #teplo kontakty
  - name: 'teplo-kontakty'
    label: 'Teplo/Kontakty'
    files:
      - label: 'Kontakty Tepla'
        name: 'teplo-kontakty'
        file: 'src/content/editable/teplo-kontakty.yml'
        format: 'yml'
        fields:
          - label: 'Kontakty'
            name: 'contacts'
            widget: 'list'
            fields:
              - { label: 'Jméno', name: 'name', widget: 'string' }
              - { label: 'Pozice', name: 'title', widget: 'string' }
              - { label: 'Ikona', name: 'icon', widget: 'string' }
              - label: 'Kontaktní informace'
                name: 'contactInfo'
                widget: 'list'
                fields:
                  - { label: 'Typ', name: 'type', widget: 'select', options: ['phone', 'email'] }
                  - { label: 'Hodnota', name: 'value', widget: 'string' }

  #kontakty
  - label: 'Kontakty'
    name: 'kontakty'
    files:
      - label: 'Kontakty'
        name: 'kontakty'
        file: 'src/content/editable/kontakty.yml'
        fields:
          - label: 'Oddělení'
            name: 'departments'
            widget: 'list'
            fields:
              - label: 'Název oddělení'
                name: 'department'
                widget: 'string'
              - label: 'Kontakty'
                name: 'contacts'
                widget: 'list'
                fields:
                  - label: 'Titul'
                    name: 'name'
                    widget: 'string'
                  - label: 'Jméno'
                    name: 'title'
                    widget: 'string'
                    required: false
                  - label: 'Ikona'
                    name: 'icon'
                    widget: 'string'
                  - label: 'Kontaktní informace'
                    name: 'contactInfo'
                    widget: 'list'
                    fields:
                      - label: 'Typ'
                        name: 'type'
                        widget: 'select'
                        options:
                          - { label: 'Telefon', value: 'phone' }
                          - { label: 'Email', value: 'email' }
                      - label: 'Hodnota'
                        name: 'value'
                        widget: 'string'

  #dokumenty
  - label: 'Dokumenty BD Kaštany'
    name: 'bd_kastany'
    folder: 'src/content/ke-stazeni'
    create: true 
    media_folder: 'public/assets/files/bd-kastany'
    public_folder: '/assets/files/bd-kastany'
    fields:
      - label: 'Název dokumentu'
        name: 'title'
        widget: 'string'
      - label: 'Soubory'
        name: 'soubory'
        widget: 'list'
        fields:
          - { label: 'Soubor', name: 'file', widget: 'file' }
          - { label: 'Datum nahrání', name: 'uploadDate', widget: 'datetime' }

  - label: 'Dokumenty BD Lípa'
    name: 'bd_lipa'
    folder: 'src/content/ke-stazeni'
    create: true
    media_folder: 'public/assets/files/bd-lipa'
    public_folder: '/assets/files/bd-lipa'
    fields:
      - label: 'Název dokumentu'
        name: 'title'
        widget: 'string'
      - label: 'Soubory'
        name: 'soubory'
        widget: 'list'
        fields:
          - { label: 'Soubor', name: 'file', widget: 'file' }
          - { label: 'Datum nahrání', name: 'uploadDate', widget: 'datetime' }

  - label: 'Dokumenty BD Pastelky'
    name: 'bd_pastelky'
    folder: 'src/content/ke-stazeni'
    create: true
    media_folder: 'public/assets/files/bd-pastelky'
    public_folder: '/assets/files/bd-pastelky'
    fields:
      - label: 'Název dokumentu'
        name: 'title'
        widget: 'string'
      - label: 'Soubory'
        name: 'soubory'
        widget: 'list'
        fields:
          - { label: 'Soubor', name: 'file', widget: 'file' }
          - { label: 'Datum nahrání', name: 'uploadDate', widget: 'datetime' }

  - label: 'Dokumenty Bytová Údržba'
    name: 'bytova_udrzba'
    folder: 'src/content/ke-stazeni'
    create: true
    media_folder: 'public/assets/files/bytova-udrzba'
    public_folder: '/assets/files/bytova-udrzba'
    fields:
      - label: 'Název dokumentu'
        name: 'title'
        widget: 'string'
      - label: 'Soubory'
        name: 'soubory'
        widget: 'list'
        fields:
          - { label: 'Soubor', name: 'file', widget: 'file' }
          - { label: 'Datum nahrání', name: 'uploadDate', widget: 'datetime' }

  - label: 'Dokumenty Obecné Dokumenty'
    name: 'obecne_dokumenty'
    folder: 'src/content/ke-stazeni'
    create: true
    media_folder: 'public/assets/files/obecne-dokumenty'
    public_folder: '/assets/files/obecne-dokumenty'
    fields:
      - label: 'Název dokumentu'
        name: 'title'
        widget: 'string'
      - label: 'Soubory'
        name: 'soubory'
        widget: 'list'
        fields:
          - { label: 'Soubor', name: 'file', widget: 'file' }
          - { label: 'Datum nahrání', name: 'uploadDate', widget: 'datetime' }

  - label: 'Dokumenty Pro Zaměstnance'
    name: 'pro_zamestnance'
    folder: 'src/content/ke-stazeni'
    create: true
    media_folder: 'public/assets/files/pro-zamestnance'
    public_folder: '/assets/files/pro-zamestnance'
    fields:
      - label: 'Název dokumentu'
        name: 'title'
        widget: 'string'
      - label: 'Soubory'
        name: 'soubory'
        widget: 'list'
        fields:
          - { label: 'Soubor', name: 'file', widget: 'file' }
          - { label: 'Datum nahrání', name: 'uploadDate', widget: 'datetime' }

  - label: 'Dokumenty Správa Prod. Bytů'
    name: 'sprava_prodanych_bytu'
    folder: 'src/content/ke-stazeni'
    create: true
    media_folder: 'public/assets/files/sprava-prodanych-bytu'
    public_folder: '/assets/files/sprava-prodanych-bytu'
    fields:
      - label: 'Název dokumentu'
        name: 'title'
        widget: 'string'
      - label: 'Soubory'
        name: 'soubory'
        widget: 'list'
        fields:
          - { label: 'Soubor', name: 'file', widget: 'file' }
          - { label: 'Datum nahrání', name: 'uploadDate', widget: 'datetime' }

  - label: 'Dokumenty Tepelné Hospodářství'
    name: 'tepelne_hospodarstvi'
    folder: 'src/content/ke-stazeni'
    create: true
    media_folder: 'public/assets/files/tepelne-hospodarstvi'
    public_folder: '/assets/files/tepelne-hospodarstvi'
    fields:
      - label: 'Název dokumentu'
        name: 'title'
        widget: 'string'
      - label: 'Soubory'
        name: 'soubory'
        widget: 'list'
        fields:
          - { label: 'Soubor', name: 'file', widget: 'file' }
          - { label: 'Datum nahrání', name: 'uploadDate', widget: 'datetime' }
